-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 03:43:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `StudentID` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `UniversityName` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `PostalCode` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`StudentID`, `Email`),
  UNIQUE INDEX `Email_UNIQUE` USING BTREE (`Email`) ,
  UNIQUE INDEX `StudentID_UNIQUE` USING BTREE (`StudentID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `TeacherID` VARCHAR(255) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Qualification` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `PostalCode` VARCHAR(45) NULL DEFAULT NULL,
  `AccountNo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`TeacherID`, `Email`),
  INDEX `TeacherID_UNIQUE` USING BTREE (`TeacherID`) ,
  INDEX `Email_UNIQUE` USING BTREE (`Email`) ,
  INDEX `AccountNo_UNIQUE` USING BTREE (`AccountNo`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `CourseID` VARCHAR(255) NOT NULL,
  `CourseName` VARCHAR(45) NOT NULL,
  `Duration` INT(11) NOT NULL,
  `TeacherID` VARCHAR(255) NOT NULL,
  `Modules` INT(11) NOT NULL,
  `TotalStudents` INT(11) NOT NULL,
  `TotalVids` INT(11) NOT NULL,
  `StudentID` VARCHAR(45) NOT NULL,
  `Grade` INT(11) NOT NULL,
  PRIMARY KEY (`CourseID`, `StudentID`),
  INDEX `StudentID_idx` (`StudentID` ) ,
  INDEX `InstructorID_idx` (`TeacherID` ) ,
  INDEX `CourseID_idx` USING BTREE (`CourseID`) ,
  CONSTRAINT `FK_StudentID`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mydb`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `course_ibfk_1`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `mydb`.`teacher` (`TeacherID`)
    ON DELETE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`discussionforum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discussionforum` (
  `CourseID` VARCHAR(255) NOT NULL,
  `Username` VARCHAR(45) NULL DEFAULT NULL,
  `Comment` TEXT NULL DEFAULT NULL,
  `Timestamp` DATETIME(6) NULL DEFAULT NULL,
  `StudentID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CourseID`, `StudentID`),
  INDEX `StudentID_idx` (`StudentID` ) ,
  CONSTRAINT `FKDF_StudentID`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mydb`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `discussionforum_ibfk_1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `mydb`.`course` (`CourseID`)
    ON DELETE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videos` (
  `CourseID` VARCHAR(255) NOT NULL,
  `URL` VARCHAR(45) NULL DEFAULT NULL,
  `Completed` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`CourseID`),
  UNIQUE INDEX `CourseID_UNIQUE` (`CourseID` ) ,
  CONSTRAINT `videos_ibfk_1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `mydb`.`course` (`CourseID`)
    ON DELETE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
